### ISSUE TITLE
Nagatoro Bug

### ISSUE THREAD

**Issue by Torben-Gullak** [doki-theme/doki-theme-visualstudio#10]
Hi,

first of all i love your Plugin, i just stumbled across it, and saw the the little Avatar of Nagatoro is buggy.
I send u a shot of it so u can see the issue!
![image](https://user-images.githubusercontent.com/91954564/136014861-c62dfb59-c13c-44ce-9bd6-b8d1fe59eb13.png)

Best Regards

Torben-Gullak

**Comment by Unthrottled** [comment]
Okay, thank you for submitting the issue. You can track the status through the original issue.

Thankfully there is a workaround, you can provide your own sticker/avatar, just [follow the documentation for setting up stickers](https://github.com/doki-theme/doki-theme-visualstudio#content-settings).
