### ISSUE TITLE
Annoying Issue Thread

### ISSUE THREAD

**Issue by Unthrottled** [doki-theme/doki-theme-visualstudio#12]
I am actually using Visual Studio now. Finna post things that I find that should be consistent.

**Comment by Unthrottled** [comment]
Identifier under caret should be themed

![image](https://user-images.githubusercontent.com/15972415/136473004-b137261a-7b8d-4ac3-9ca8-85550ebe78ce.png)

**Comment by Unthrottled** [comment]
Refactoring identifier is almost unusable

![image](https://user-images.githubusercontent.com/15972415/136473042-61744f58-f988-4512-b0ec-5dc7f2d8e352.png)

**Comment by avail** [comment]
`Appears to be tied to this, just dunno the property to set.`
in the vstheme file it's pretty much just plaintext however idk how exactly you're applying values
```
      <Color Name="Inline Rename Field Text">
        <Background Type="CT_INVALID" Source="00000000" />
        <Foreground Type="CT_INVALID" Source="00000000" />
      </Color>
```

**Comment by Unthrottled** [comment]
@avail That was the right property. Just had to switch some things around and it works, thanks!
