### ISSUE TITLE
Couldn’t get Sticker & Wallpaper to work on Visual Studios 2022 professional 17.0 (non preview - official version)

### ISSUE THREAD

**Issue by leekahwai** [doki-theme/doki-theme-visualstudio#22]
As described in title. Unable to get it to work on visual studios 2022 professional 17.0. The general theme colours and icons are updated. But the sticker, wallpaper and opacity does not take effect. 

It works on Visual Studios 2022 Community version on another machine. 
The Professional version is running in offline environment. Did something gets downloaded during the installation of the extension?

I've tried the open new file. It only works for the community version.

**Comment by Unthrottled** [comment]
> The Professional version is running in offline environment. Did something gets downloaded during the installation of the extension?

Yes, when a theme is selected, content is downloaded from the CDN, so you'll need to be online at least when you set the theme for the first time.

Have you tried setting [custom content?](https://github.com/doki-theme/doki-theme-visualstudio#content-settings) (CustomWallpaperImageAbsolutePath, and CustomStickerImageAbsolutePath) That works offline.

If not I'll link something for you to probably try. I think I have the plugin only targeted for community, I wonder if I can target both professional & community.

**Comment by leekahwai** [comment]
Custom content works. I think it's fine. I can download my own stickers and wallpapers 😀
