### ISSUE TITLE
Theme Improvements (Darkness Dark Theme) VS 2022

### ISSUE THREAD

**Issue by ElrohirGT** [doki-theme/doki-theme-visualstudio#27]
Hello! I've found some problems with some themes, particularly the darkness theme and probably other dark themes with blackish background, for example the notifications are almost unreadeable at best, the gif below showcases this issue. I think this is kind of a major problem. I've tried other dark themes for example the Emilia Dark, and it doesn't look that bad in that theme.
![VSNotification](https://user-images.githubusercontent.com/45268815/142436955-9d3ef752-5a97-4ac5-9044-d7e0a9dc3ee9.gif)
![VSBuildNotificationEmilia](https://user-images.githubusercontent.com/45268815/142439400-5d5ce01c-68d1-4f19-9074-fd3a874e6d36.gif)

Another problem I've found has to do with the status bar, because when building the project it changes color, I think it changes to the default color but I'm not sure. The gif below showcases this issue. I think this is probably a bug, because the Mai Dark theme doesn't have this problem but the Emilia dark does.
![VSBuildStatusBar](https://user-images.githubusercontent.com/45268815/142436597-82c23fca-f1eb-4b95-a231-cb08dd584aa1.gif)

Cheers man, I'm really loving this themes!

**Comment by Unthrottled** [comment]
I'll try harder this time to fix the notification background. I noticed the issue when I was building the themes, but gave up after a couple of attempts. So that one is my bad.

> Another problem I've found has to do with the status bar, because when building the project it changes color..

Just to make sure I understand the issue. In the gif presented, it is the brief coloration of `Build Started` that is white on orange before it turns blue that you are wanting fixed?

Thanks for taking the time to submit this issue, I appreciate it!

**Comment by Unthrottled** [comment]
> Another problem I've found has to do with the status bar, because when building the project it changes color..

Ah, I think you might have been talking about how it changes to blue while building, but goes back to the regular color. That was done intentionally to denote state change. I am willing to revisit the coloration though.

As an example

https://user-images.githubusercontent.com/15972415/142791993-ae66ed9a-0815-4eb0-9803-4eecfc4ece22.mp4
