### ISSUE TITLE
problems with the scale of the wallpaper

### ISSUE THREAD

**Issue by chrlkru** [doki-theme/doki-theme-visualstudio#28]
Unfortunately, I have problems with the scale of both and they climb out of the eran and get clipped :(
Perhaps this is due to the screen size of 15.6 or its 1080P resolution. If you can fix it it would be great.
![image](https://user-images.githubusercontent.com/62420753/142775483-50b13b06-874d-4135-8a2a-35fee3fd60fb.png)

**Comment by Unthrottled** [comment]
I think this may be related to #8 will look into a potential work around.

**Comment by chrlkru** [comment]
Thanks

чт, 25 нояб. 2021 г., 18:42 Alex Simons ***@***.***>:
