### ISSUE TITLE
Stickers and Wallpapers dont work

### ISSUE THREAD

**Issue by AdvancedGP** [doki-theme/doki-theme-visualstudio#32]
i installed the plugin, then uninstalled ClaudiaIDE since i had it, i changed to "Rias Crimson" theme and the colors work, but no sticker or wallpaper even though they are set to "true" in the doki settings, i tried manually linking them by finding the pictures and setting the path manually but that does not seem to work either.

Me setting paths manually:
https://imgur.com/a/aIxlEvg

**Comment by Unthrottled** [comment]
That's a bit curious. Could you answer these questions for me, please?

- What version of Visual Studio are you using?
- What version of the plugin did you install?

**Comment by AdvancedGP** [comment]
> That's a bit curious. Could you answer these questions for me, please?
> 
> * What version of Visual Studio are you using?
> * What version of the plugin did you install?

VS 2022
Doki V2.2.0

should be the correct versions.
also, some new info i found, if i open the IDE/.cs file through Unity Engine OR by a finding the file by itself on my desktop, the sticker and wallpaper WONT appear.
BUT, if i open the IDE/.cs file through the VA 2022 launcher (just searching up Visual Studio 2022 Current on the windows search bar or something, and then click on my file which is under my "open recent" tab) then the stickers and wallpapers WILL appear.

Opening file through here will work:
https://imgur.com/a/Y8jUqel

and opening through both of these methods do not work:
https://imgur.com/a/soPorTl

**Comment by Unthrottled** [comment]
Thanks for the supporting information!
I am fairly confident it is related to this issue https://github.com/doki-theme/doki-theme-visualstudio/issues/6#issuecomment-897197288

When I get around to updating this plugin in the near future, I'll look harder into solving this issue. Thanks for your patience!

**Comment by AdvancedGP** [comment]
> Thanks for the supporting information! I am fairly confident it is related to this issue [#6 (comment)](https://github.com/doki-theme/doki-theme-visualstudio/issues/6#issuecomment-897197288)
> 
> When I get around to updating this plugin in the near future, I'll look harder into solving this issue. Thanks for your patience!

seems like your right.
