### ISSUE TITLE
Missing tab highlight in NuGet Package Manager

### ISSUE THREAD

**Issue by zsuatem** [doki-theme/doki-theme-visualstudio#36]
Missing tab highlight in NuGet Package Manager

Default Dark theme
![devenv_1GkdFr8b8x](https://user-images.githubusercontent.com/17302628/148605636-70b0c0c9-80d7-48d6-82be-e33d0bc33a30.png)

Doki-Theme
![image](https://user-images.githubusercontent.com/17302628/148605738-2fddecdb-ff69-42a7-8aef-100b648fed1f.png)

**Comment by Unthrottled** [comment]
Link to property for future reference:

https://github.com/NuGet/NuGet.Client/blob/5886341d8d004ecc9f6951bc60060eb0bc366828/src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageManagerTopPanel.xaml#L65
