### ISSUE TITLE
Missing hover item highlight in search menu

### ISSUE THREAD

**Issue by zsuatem** [doki-theme/doki-theme-visualstudio#38]
Missing hover item highlight in search menu

Default Dark theme
![HEK3PY16Zd](https://user-images.githubusercontent.com/17302628/148607553-712d0250-d585-4fe2-b8c7-09bb663601fa.png)

Doki-Theme
![sATU17LAG4](https://user-images.githubusercontent.com/17302628/148607585-dbaf4b61-875f-4450-ba3a-e1496e9771e9.png)

**Comment by Unthrottled** [comment]
Thank you for taking the time to report these issues. 

I believe I've got most of them fixed, and I also published the release with the fixes in it. That should be available now, let me know if it isn't, thanks!
