### ISSUE TITLE
Text on non-code editor windows with overwritten background doesn't respect Dark/Light setting

### ISSUE THREAD

**Issue by neneeen** [doki-theme/doki-theme-visualstudio#39]
I have https://marketplace.visualstudio.com/items?itemName=MichaelKissBG8.Supercharger22 installed, which add a code map on the left of the code editor https://supercharger.tools/index.html#sectionCodeMAP

With dark themes, on initial load, the code map looks like this 
![image](https://user-images.githubusercontent.com/59354331/148623185-f40806d9-7034-43f1-890a-094c4ef63e1e.png), the background doesn't extend to the code map, which is not too nice, but at least usable, and much better than after a while when the code map looks like this
![image](https://user-images.githubusercontent.com/59354331/148623256-e63f1dc4-aa13-4fd9-8d86-61629cfaf1a4.png)

The text seems to default to black. Weirdly enough this happens even with themes not provided by Doki Theme, such as the default Black
![image](https://user-images.githubusercontent.com/59354331/148623365-9a0c970c-e31b-44b6-b390-7a236ae740ae.png)

With doki theme disabled, the text on the code map is correctly displayed
![image](https://user-images.githubusercontent.com/59354331/148623586-906cd1f9-84eb-4e49-ae4c-ed91a133f0f1.png)

If there's no way to tell the code map to respect the dark light setting because it's generated by another extension, is there a way to at least disable the background overwriting altogether for non-code editor windows?

**Comment by Unthrottled** [comment]
Hi! 

Can you answer these questions for me, please?

- What version of Visual Studio are you using?
- What version of the Doki Theme are you using?
- What version of the Supercharger plugin are you using?
- What operating system are you using? (windows 10?)

I'll look into trying to reproduce the issue.

**Comment by neneeen** [comment]
VS is 17.0.4 with rich client and graphic acceleration enabled, Doki is 3.0.0, Supercharger is 1.12.0.1600, Windows 10 21H2 19044.1415

**Comment by Unthrottled** [comment]
Thank you for providing the supporting information!

I am having trouble replicating the text becoming black/background image drawing on the background.

Is there a way you can reproduce it? 
I know you said that: `than after a while when the code map looks like this`, does it happen after you do something or is it just after time passes?

**Comment by neneeen** [comment]
The time varies, sometimes it just happens by itself almost immediately, less than 15 seconds, sometimes it seems to take a while, maybe 1-2 minutes. Doesn't seem to care whether I'm typing in the window or not. Does closing and opening the window still gives you no image drawing in the background? Perhaps Supercharger is configured differently on a new install, mine carries the previous profile, I do try resetting the Supercharger profile, but the problem persists.

Steps to reproduce, with all other VS extensions disabled except Supercharger & Doki :

1. Create a new C# .NET 6 Console project
2. Add a new method to test the code map
![image](https://user-images.githubusercontent.com/59354331/148665694-35e4e1e1-3c5e-4105-99a5-995a3b7d9bb9.png)


I do find a workaround just now, it turns out in the Supercharger options, on the CodeMAP - Visual - Theme, there are radio buttons for
* Mimic the code edit window
* Specific, with dropdown for various Light mode and one Dark mode

In my install, the Mimic option is selected, changing it to Specific Light/Dark disable the background image on the code map, and the text does follow the Specific setting. 
![image](https://user-images.githubusercontent.com/59354331/148665719-4533782a-9e04-424b-bfd1-87326ff0143d.png)


If your install is in the Mimic option, I guess it's the Supercharger's fault in detecting whether the current theme is dark/light. Either way, the problem is with Supercharger. Thank you for the support!
