### ISSUE TITLE
"Tab" title background color.

### ISSUE THREAD

**Issue by nickclark2016** [doki-theme/doki-theme-visualstudio#43]
When I run Visual Studio with a theme, I'm running into an issue where there is no theme applied on the background of the title in the "tabs" pane.  To reproduce, set your tab layout to place tabs on the left or right.

Expected Behavior: I expect the default background color to be applied to the background of the "Tabs" pane title region.

Picture showing problem:
![image](https://user-images.githubusercontent.com/17892116/163728910-0e278789-6e87-4b03-9e64-40c16417c8bd.png)
(Shown on Raphtalia theme)

**Comment by Unthrottled** [comment]
Alright, I got that fixed, that was a fun game of playing `find the needle in the haystack`.

![image](https://user-images.githubusercontent.com/15972415/163889489-db0f4337-8743-4ed2-a426-03e3a0388607.png)

Thanks for taking the time to report the issue . I published the version with the fix to the visual studio marketplace, it should be available shortly, so you can update.

**Comment by nickclark2016** [comment]
Thank you for getting out a fix so quickly.  I can go back to having tabs on the left in peace :)
