### ISSUE TITLE
Background color in SQL editor doesn't match theme

### ISSUE THREAD

**Issue by beleester** [doki-theme/doki-theme-visualstudio#45]
If you open a SQL file in Visual Studio, the editor has a black background, which makes it unreadable with light themes.  Example with Satsuki Light theme:

![image](https://user-images.githubusercontent.com/2622011/165163621-56b50c55-cb8f-46ed-8cb5-506b6c1ad1dd.png)

**Comment by Unthrottled** [comment]
Thanks for taking the time to report the issue, it looks like it might be related to #21 . Are SQL files the only one's currently impacted by this issue?

I'll have some time in the near future to look into the fix, thanks!

**Comment by Unthrottled** [comment]
Hey! I am not able to replicate the the issue

![image](https://user-images.githubusercontent.com/15972415/166160483-ffe44cf7-8259-43ea-a9fa-98fe4bae2663.png)

Are you using an extension that does stuff with SQL files?

**Comment by beleester** [comment]
Apparently I have "SQL Server Data Tools - SQL Editor" installed.  That looks relevant.

I can't find where its colors get configured in the Options menu.

**Comment by Unthrottled** [comment]
Got it, thank you!

> I can't find where its colors get configured in the Options menu

This is most likely a side effect of how the wallpaper gets added to the editor background.

**Comment by Unthrottled** [comment]
Hey! I think I've got the issue fixed. I still wasn't able to get the same view you showed in your screen shot. If you could upgrade the extension to `78.1.2`, and see if it fixed the issue.

If it didn't get fixed, then could you give me some details as to how to open that view? I don't really use Visual Studio, so I'm not very familiar with its functionality. Thanks!

**Comment by beleester** [comment]
This appears to have fixed it!  Thank you.
