### ISSUE TITLE
Sticker sizing when using ctrl+scroll

### ISSUE THREAD

**Issue by Averag3Mang0** [doki-theme/doki-theme-visualstudio#46]
is there any way to fix this issue?

**Comment by Unthrottled** [comment]
Are you wanting to be able to control the size of the sticker?

**Comment by Unthrottled** [comment]
@IchimakiKasura Ah that makes sense. Never tried changing the font size.

When I get time, I'll look into not making it scale as font scale, and add a way to make the sticker get out of the way. Thanks!
