### ISSUE TITLE
Wallpaper does not work if wallpaper opacity set between "-0.9" and "0"

### ISSUE THREAD

**Issue by qwerty1874** [doki-theme/doki-theme-visualstudio#52]
Wallpaper does not work if wallpaper opacity set between "-0.9" and "0"

VS 2022 community 17.3.3

**Comment by Unthrottled** [comment]
Ah, I worded things incorrectly.

The list of acceptable values are -1, and any number between 0 and 1.

I'll update the docs & see if I can't prevent numbers between -0.99 & -.01 from being entered. As negative transparency doesn't make sense.
