### ISSUE TITLE
Wallpaper colour changes

### ISSUE THREAD

**Issue by Dantrix846** [doki-theme/doki-theme-visualstudio#53]
Umm... is there any way to change the wallpaper colour without changing the wallpaper character. I really like the "Nakano Ichika" theme, but it's too light...

**Comment by Unthrottled** [comment]
Hmm, you could:

- [Download the asset](https://github.com/doki-theme/doki-theme-assets/blob/master/backgrounds/ichika_light.png)
- [Use the CustomWallpaperImageAbsolutePath](https://github.com/doki-theme/doki-theme-visualstudio#wallpapers)
- Choose another Purple Theme ex: Tsubasa Hanekawa, Jahy, Yuri Dark, Emilia Dark, etc.

That what you after?

**Comment by Dantrix846** [comment]
Ummm... I like the wallpaper "image" if you understand but im after darker
base colour like dark purplr, blue, or gray.

Dne út 1. 11. 2022 0:38 uživatel Alex Simons ***@***.***>
napsal:

**Comment by Unthrottled** [comment]
Yes, that's what I was suggesting, sorry for not making it a numbered list to indicate that it's the steps you need to do in order to use the same image but on a different theme.

**Comment by Dantrix846** [comment]
Oh, thank you really much, sorry if i sounded rude, english is not my
native language. Love your work!
----
Daniel Pravdík 16

út 1. 11. 2022 v 12:26 odesílatel Alex Simons ***@***.***>
napsal:

**Comment by Unthrottled** [comment]
No worries :)

Glad I could provide a work around that is suitable for you. Let me know if you need any clarifications. Thanks!
