### ISSUE TITLE
Not visible both background and sticker!

### ISSUE THREAD

**Issue by tyxefield** [doki-theme/doki-theme-visualstudio#6]
![Captura](https://user-images.githubusercontent.com/40292352/129096478-adc8e3de-76ab-476a-b1c7-20e579bb4826.PNG)

It happened two times in a row, they have the visibility check and opacity up, i have to install it back and sometimes doesn't want to work, i'm using Visual Studio Community 2019, i'm not using any custom plugin for themes or backgrounds.

I love this a lot! But i don't know how to fix this problem.

Hope there's a fix to this 👍

**Comment by Unthrottled** [comment]
Does the sticker and wallpaper come back if you close the file tab and open it back up?
I've noticed when I first start it up, that they don't show up, but if you open a new file they appear on the newly opened file.

**Comment by tyxefield** [comment]
> Does the sticker and wallpaper come back if you close the file tab and open it back up?
> I've noticed when I first start it up, that they don't show up, but if you open a new file they appear on the newly opened file.

**That fixed it! Thank you very much <3
This is the best plugin i've ever seen for visual, honestly lol**

**Comment by Unthrottled** [comment]
When I get some time, I'll try to get to try retry to put the stickers/background on start up, or if I give up, offer a `Re-Paint` option that manually put the stuff on all the open windows. The plugin has some interesting async loading issues. 

I'll close this issue once I've done that. 

Thanks for the kind words and dealing with this issue for the time being!

**Comment by Unthrottled** [comment]
So I've got the issue mitigated a bit better. You can find out the new behaviour here https://github.com/doki-theme/doki-theme-visualstudio/tree/main#weird-bugs

If I ever get more knowledge about how the Visual Studio SDK works better, then I might get it to become more responsive (load quicker/work better). Until then, this is what I got.

![It aint much](https://i.kym-cdn.com/entries/icons/original/000/028/021/work.jpg)
