### ISSUE TITLE
The extension can't be used on VS 2022 Preview

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-visualstudio#7]
I was wondering if is possible to update the extension to add support for VS 2022.

![image](https://user-images.githubusercontent.com/11861253/129514863-987a81fa-8c51-4161-8192-5c320a136546.png)

**Comment by Unthrottled** [comment]
Probably, I'll look into this when I get the time. Didn't know there was a preview build.

**Comment by kotx** [comment]
BTW, you can use this now for VS2022: https://github.com/microsoft/theme-converter-for-vs
Would be cool if releases could be based on this if that would be better.

**Comment by justalemon** [comment]
> Would be cool if releases could be based on this if that would be better.

Why would it be better? As far as I know, @Unthrottled has it's own scripts to convert the themes from doki-theme-master to all different target Code Editors, IDEs and Terminal Consoles.

**Comment by kotx** [comment]
> Why would it be better? As far as I know, @Unthrottled has it's own scripts to convert the themes from doki-theme-master to all different target Code Editors, IDEs and Terminal Consoles.

If they have their own scripts then that's fine. However the ones I linked might be better and/or contain more features. Ultimately the benefits and drawbacks will have to be weighed.

**Comment by Unthrottled** [comment]
> you can use this now for VS2022: https://github.com/microsoft/theme-converter-for-vs

Cool, I'll have to look into that. Generating the theme.xml was a pain in the butt. This might come in handy for adding the light themes in, or if I need to port the dark themes if they changed a bunch of things. 

> scripts to convert the themes from doki-theme-master to all different target Code Editors, IDEs and Terminal Consoles.

I does has that, however, they are all customized to each artifact that needs to be created. This converter might be helpful if I need to generate the initial theme artifact for Visual Studio.


Anyways, I'll have some time to port this over to vs 2022 when I work on publishing [my new themes](https://github.com/doki-theme/doki-master-theme/milestone/8) to all the platforms. 

Thanks all.
