### ISSUE TITLE
Wallpaper is cut off when a window is placed under the editor window

### ISSUE THREAD

**Issue by nashinium** [doki-theme/doki-theme-visualstudio#8]
If you place a window such as powershell underneath the editor, the wallpaper will be cut off.
*before*
![Before](https://cdn.discordapp.com/attachments/717367401624371311/877181336786452500/PPPUCpp2ndJP_-_Microsoft_Visual_Studio_8_17_2021_5_42_47_PM.png)
*after i added powershell windows underneath the editor*
![After](https://cdn.discordapp.com/attachments/717367401624371311/877181340863324180/PPPUCpp2ndJP_-_Microsoft_Visual_Studio_8_17_2021_5_47_38_PM.png)

It would be nice if the wallpaper could be uninterrupted, like doki-theme-vscode, and the powershell window could be transparent so that you could see the wallpaper, but I don't know how to make that happen.

**Comment by Unthrottled** [comment]
I can't see the links that you posted, but I think I know what you are talking about.

I wanted the same thing as well, however, there was a way I could have done it, but it would not have looked as good as VS Code's wallpaper feature, plus there is a lot of things to make transparent. So the wallpaper is just part of the editor window.

I probably will not make the wallpaper draw on all of the IDE, but I'll leave this issue open if I change my mind.

If you want, you can turn off the wallpaper rendering of this extension, and use [Claudia IDE](https://github.com/buchizo/ClaudiaIDE#how-to-expand-to-ide), you'll have to do the work of making things transparent though.

**Comment by nashinium** [comment]
Sorry that the image links did not work properly. I have just made the change.
And thanks for the great advice. But I like this extension better, so I'll think about installing Claudia IDE when I feel like it.

Thank you for sending your gracious response so promptly <3
